//! SDP offer/answer/hold/resume builders, plus the ICE/SRTP line-rendering
//! helpers shared with `video.rs`.

use super::codec::{ALL_CODECS, AudioCodec, CN_PAYLOAD_TYPE};
use super::srtp::SrtpParams;

/// ICE parameters for one side of a call, gathered/generated by
/// `deelip_nat::ice` and embedded in an offer/answer. Kept as a plain struct
/// here (no dependency on `deelip-nat`) — same "protocol-layer crates stay
/// decoupled from the app-level glue" reasoning already used for
/// `AudioCodec`/`SipAccount::codec_order`. `candidates` are already
/// fully-formed RFC 8839 values (from `Candidate::marshal()`), just missing
/// the `a=candidate:` line prefix.
pub struct IceAttrs {
    pub ufrag: String,
    pub pwd: String,
    pub candidates: Vec<String>,
}

pub(super) fn savp_profile(srtp: Option<&SrtpParams>) -> &'static str {
    if srtp.is_some() { "RTP/SAVP" } else { "RTP/AVP" }
}

pub(super) fn crypto_lines(srtp: Option<&SrtpParams>) -> String {
    srtp.map(|s| s.to_crypto_line(1)).unwrap_or_default()
}

pub(super) fn ice_lines(ice: Option<&IceAttrs>) -> String {
    let Some(ice) = ice else { return String::new() };
    let mut out = format!("a=ice-ufrag:{}\r\na=ice-pwd:{}\r\n", ice.ufrag, ice.pwd);
    for c in &ice.candidates {
        out.push_str(&format!("a=candidate:{c}\r\n"));
    }
    out
}

fn rtpmap_and_fmtp_lines(codec: AudioCodec) -> String {
    let pt = codec.payload_type();
    let mut out = format!("a=rtpmap:{pt} {}\r\n", codec.rtpmap());
    if let Some(fmtp) = codec.fmtp() {
        out.push_str(&fmtp);
    }
    out
}

/// Build an SDP offer listing `codecs` in the given preference order (falls
/// back to `ALL_CODECS` if empty — defensive only, see `ALL_CODECS`'s doc).
/// `ice`, if given, adds `a=ice-ufrag`/`a=ice-pwd`/`a=candidate` lines
/// alongside the plain `c=`/`m=` address (which stays populated with our
/// best candidate regardless, so a peer that ignores ICE still works).
pub fn build_offer(
    local_ip: &str, rtp_port: u16, srtp: Option<&SrtpParams>, codecs: &[AudioCodec], ice: Option<&IceAttrs>,
    vad_enabled: bool,
) -> String {
    let sid = now_ntp();
    let codecs: &[AudioCodec] = if codecs.is_empty() { &ALL_CODECS } else { codecs };
    // Only offered if at least one candidate codec shares CN's 8000 Hz
    // clock -- see `CN_PAYLOAD_TYPE`'s doc comment. If the answerer ends up
    // choosing Opus anyway, `MediaEngine` separately re-checks the actually
    // negotiated codec before ever using this.
    let advertise_cn = vad_enabled && codecs.iter().any(|&c| c != AudioCodec::Opus);
    let pt_list: String = codecs.iter().map(|c| c.payload_type().to_string()).collect::<Vec<_>>().join(" ");
    let codec_lines: String = codecs.iter().map(|&c| rtpmap_and_fmtp_lines(c)).collect();
    let profile = savp_profile(srtp);
    let cn_pt_suffix = if advertise_cn { format!(" {CN_PAYLOAD_TYPE}") } else { String::new() };
    let cn_line = if advertise_cn { format!("a=rtpmap:{CN_PAYLOAD_TYPE} CN/8000\r\n") } else { String::new() };
    format!(
        "v=0\r\n\
         o=- {sid} {sid} IN IP4 {local_ip}\r\n\
         s=-\r\n\
         c=IN IP4 {local_ip}\r\n\
         t=0 0\r\n\
         m=audio {rtp_port} {profile} {pt_list} 101{cn_pt_suffix}\r\n\
         {codec_lines}\
         a=rtpmap:101 telephone-event/8000\r\n\
         a=fmtp:101 0-15\r\n\
         {cn_line}\
         {crypto}\
         {ice_lines}\
         a=ptime:20\r\n\
         a=sendrecv\r\n",
        crypto = crypto_lines(srtp),
        ice_lines = ice_lines(ice),
    )
}

/// Build an SDP answer, selecting the negotiated voice `codec`.
/// telephone-event is included if the offer contained it.
pub fn build_answer(
    local_ip: &str, rtp_port: u16, codec: AudioCodec, srtp: Option<&SrtpParams>, ice: Option<&IceAttrs>,
    vad_enabled: bool,
) -> String {
    let sid = now_ntp();
    let pt = codec.payload_type();
    let profile = savp_profile(srtp);
    // See `CN_PAYLOAD_TYPE`'s doc comment for why this excludes Opus.
    let advertise_cn = vad_enabled && codec != AudioCodec::Opus;
    let pt_suffix = if advertise_cn { format!(" {CN_PAYLOAD_TYPE}") } else { String::new() };
    let cn_line = if advertise_cn { format!("a=rtpmap:{CN_PAYLOAD_TYPE} CN/8000\r\n") } else { String::new() };
    format!(
        "v=0\r\n\
         o=- {sid} {sid} IN IP4 {local_ip}\r\n\
         s=-\r\n\
         c=IN IP4 {local_ip}\r\n\
         t=0 0\r\n\
         m=audio {rtp_port} {profile} {pt} 101{pt_suffix}\r\n\
         {codec_lines}\
         a=rtpmap:101 telephone-event/8000\r\n\
         a=fmtp:101 0-15\r\n\
         {cn_line}\
         {crypto}\
         {ice_lines}\
         a=ptime:20\r\n\
         a=sendrecv\r\n",
        codec_lines = rtpmap_and_fmtp_lines(codec),
        crypto = crypto_lines(srtp),
        ice_lines = ice_lines(ice),
    )
}

/// Build a hold SDP (a=sendonly) for re-INVITE.
pub fn build_hold_offer(local_ip: &str, rtp_port: u16, codec: AudioCodec, srtp: Option<&SrtpParams>) -> String {
    let sid = now_ntp();
    let pt = codec.payload_type();
    let profile = savp_profile(srtp);
    format!(
        "v=0\r\n\
         o=- {sid} {sid} IN IP4 {local_ip}\r\n\
         s=-\r\n\
         c=IN IP4 {local_ip}\r\n\
         t=0 0\r\n\
         m=audio {rtp_port} {profile} {pt} 101\r\n\
         {codec_lines}\
         a=rtpmap:101 telephone-event/8000\r\n\
         a=fmtp:101 0-15\r\n\
         {crypto}\
         a=ptime:20\r\n\
         a=sendonly\r\n",
        codec_lines = rtpmap_and_fmtp_lines(codec),
        crypto = crypto_lines(srtp),
    )
}

/// Build a resume SDP (a=sendrecv) for re-INVITE.
pub fn build_resume_offer(local_ip: &str, rtp_port: u16, codec: AudioCodec, srtp: Option<&SrtpParams>) -> String {
    let sid = now_ntp();
    let pt = codec.payload_type();
    let profile = savp_profile(srtp);
    format!(
        "v=0\r\n\
         o=- {sid} {sid} IN IP4 {local_ip}\r\n\
         s=-\r\n\
         c=IN IP4 {local_ip}\r\n\
         t=0 0\r\n\
         m=audio {rtp_port} {profile} {pt} 101\r\n\
         {codec_lines}\
         a=rtpmap:101 telephone-event/8000\r\n\
         a=fmtp:101 0-15\r\n\
         {crypto}\
         a=ptime:20\r\n\
         a=sendrecv\r\n",
        codec_lines = rtpmap_and_fmtp_lines(codec),
        crypto = crypto_lines(srtp),
    )
}

fn now_ntp() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs() + 2_208_988_800
    // seconds from NTP epoch (1900) to Unix epoch (1970)
}
